/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Upload/Avatar.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    Collapse: typeof import('./components/common/Collapse.vue')['default']
    CommonBaiduMap: typeof import('./components/Theme/Components/CommonBaiduMap.vue')['default']
    CommonEditor: typeof import('./components/Theme/Components/CommonEditor.vue')['default']
    CommonImageCarousel: typeof import('./components/Theme/Components/CommonImageCarousel.vue')['default']
    CommonImageMulti: typeof import('./components/Theme/Components/CommonImageMulti.vue')['default']
    CommonImageSingle: typeof import('./components/Theme/Components/CommonImageSingle.vue')['default']
    CommonImageText: typeof import('./components/Theme/Components/CommonImageText.vue')['default']
    CommonLogo: typeof import('./components/Theme/Components/CommonLogo.vue')['default']
    CommonMenu: typeof import('./components/Theme/Components/CommonMenu.vue')['default']
    CommonMessage: typeof import('./components/Theme/Components/CommonMessage.vue')['default']
    CommonMultiImageText: typeof import('./components/Theme/Components/CommonMultiImageText.vue')['default']
    CommonReadContent: typeof import('./components/Theme/Components/CommonReadContent.vue')['default']
    CommonText: typeof import('./components/Theme/Components/CommonText.vue')['default']
    CommonVideo: typeof import('./components/Theme/Components/CommonVideo.vue')['default']
    Ebtn: typeof import('./components/common/Ebtn.vue')['default']
    EBtn: typeof import('./components/common/EBtn.vue')['default']
    Editor: typeof import('./components/common/Editor.vue')['default']
    Error: typeof import('./components/common/Error.vue')['default']
    Footer: typeof import('./components/Footer/src/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ImageTextDialog: typeof import('./components/Upload/Modules/ImageTextDialog.vue')['default']
    Logo: typeof import('./components/common/Logo.vue')['default']
    Menu: typeof import('./components/Menu/src/Menu.vue')['default']
    ModuleLink: typeof import('./components/Theme/Components/Modules/ModuleLink.vue')['default']
    ModuleReadContent: typeof import('./components/Theme/Components/Modules/ModuleReadContent.vue')['default']
    ModuleSubMenu: typeof import('./components/Theme/Components/Modules/ModuleSubMenu.vue')['default']
    Pagination: typeof import('./components/common/Pagination.vue')['default']
    PaginationSimple: typeof import('./components/common/PaginationSimple.vue')['default']
    Preference: typeof import('./components/common/Preference.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabMenu: typeof import('./components/TabMenu/src/TabMenu.vue')['default']
    TagsView: typeof import('./components/TagsView/src/TagsView.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    UploadMultiImage: typeof import('./components/Upload/UploadMultiImage.vue')['default']
    UploadMultiImageText: typeof import('./components/Upload/UploadMultiImageText.vue')['default']
    UploadSingleImage: typeof import('./components/Upload/UploadSingleImage.vue')['default']
    UploadVideo: typeof import('./components/Upload/UploadVideo.vue')['default']
    UserInfo: typeof import('./components/common/UserInfo.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
